### ISSUE TITLE
Setting up simulation for different stabilities and turbulent intensity

### ISSUE THREAD

**Issue by AsimUdel** [lawrenceccheung/AWAKEN_summit_setup#1]
Hi @lawrenceccheung , 
I hope you are doing great, thank you so much for these files, indeed these are very helpful for the new users of AMR-Wind like me. I have a quick question regarding how to setup a simulation for different atmospheric stabilities (i.e., neutral, stable and unstable) and different turbulent intensity (TI) in the input file of AMR-Wind ? e.g., like you did for (Medium Wind speed and Low TI) (https://github.com/lawrenceccheung/ALCC_Frontier_WindFarm/blob/main/farmruns/MedWS_LowTI/template/MedWS_LowTI_precursor1_spectra.inp) (if there is any documentation or literature), kindly let me know. Thank you

**Comment by lawrenceccheung** [comment]
Hi @AsimUdel,

This is a great question, there are a couple of ways to accomplish what you want.  One way is to iteratively try different precursor conditions until you find one that is acceptably close to the desired conditions.  We've done this in the past, and in such a case, you use the `ABLForcing` feature to define the hub-height wind speed and direction that you want to set.  Then you iteratively try different surface roughnesses `ABL.surface_roughness_z0` and the surface temperature rate `ABL.surface_temp_rate` (also the surface temp flux if necessary) until the right hub-height shear or TI levels are reached.

You can see an example how such an ABL approach is used to find the right boundary conditions matching a specific here:
https://github.com/lawrenceccheung/ALCC_Frontier_WindFarm/blob/main/precursor/MedWS_LowTI/Postprocessing_MedWS_LowTI1.ipynb.

This method does take quite a few tries and can be laborious, since stable or unstable ABL do not necessarily reach a steady state, and some ABL conditions can be hard to reach.  Hopefully this helps give you some idea, though.

Lawrence

**Comment by AsimUdel** [comment]
Thank you so much @lawrenceccheung , for the detail response. I will surely look into the example you provided and follow those steps.
